esphome:
  name: p1meter
  comment: "P1 module to read smart meter"
  platform: ESP32
  board: esp32dev

# Enable logging
logger:
  baud_rate: 0
 
# Enable Home Assistant API
api:
 
ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  power_save_mode: none

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "P1Meter Fallback Hotspot"
    password: "p1meter!"

captive_portal:

web_server:
  port: 80

uart:
  baud_rate: 115200
  rx_pin: 16

dsmr:
  id: dsmr_instance
#  decryption_key: !secret decryption_key

sensor:
  - platform: dsmr
    energy_delivered_lux:
      name: "Energy Consumed Luxembourg"
      state_class: total_increasing
    energy_delivered_tariff1:
      name: "Energy Consumed Tariff 1"
      state_class: total_increasing
    energy_delivered_tariff2:
      name: "Energy Consumed Tariff 2"
      state_class: total_increasing
    energy_returned_lux:
      name: "Energy Produced Luxembourg"
      state_class: total_increasing
    energy_returned_tariff1:
      name: "Energy Produced Tariff 1"
      state_class: total_increasing
    energy_returned_tariff2:
      name: "Energy Produced Tariff 2"
      state_class: total_increasing
    power_delivered:
      name: "Power Consumed"
    power_returned:
      name: "Power Produced"
    electricity_failures:
      name: "Electricity Failures"
      icon: mdi:alert
    electricity_long_failures:
      name: "Long Electricity Failures"
      icon: mdi:alert
    voltage_l1:
      name: "Voltage Phase 1"
    voltage_l2:
      name: "Voltage Phase 2"
    voltage_l3:
      name: "Voltage Phase 3"
    current_l1:
      name: "Current Phase 1"
    current_l2:
      name: "Current Phase 2"
    current_l3:
      name: "Current Phase 3"
    power_delivered_l1:
      name: "Power Consumed Phase 1"
    power_delivered_l2:
      name: "Power Consumed Phase 2"
    power_delivered_l3:
      name: "Power Consumed Phase 3"
    power_returned_l1:
      name: "Power Produced Phase 1"
    power_returned_l2:
      name: "Power Produced Phase 2"
    power_returned_l3:
      name: "Power Produced Phase 3"
    gas_delivered:
      name: "Gas Consumed"
      state_class: total_increasing
    gas_delivered_be:
      name: "Gas Consumed Belgium"
      state_class: total_increasing
  - platform: uptime
    name: "P1Meter Uptime"
  - platform: wifi_signal
    name: "P1Meter Wi-Fi Signal"
    update_interval: 60s

text_sensor:
  - platform: dsmr
    identification:
      name: "DSMR Identification"
    p1_version:
      name: "DSMR Version"
    p1_version_be:
      name: "DSMR Version Belgium"
  - platform: wifi_info
    ip_address:
      name: "IP Address"
    ssid:
      name: "Wi-Fi SSID"
    bssid:
      name: "Wi-Fi BSSID"
